app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/PastOrder.jsx, app/js/components/orderEntry/PastOrders.jsx, tests/components/orderentry/PastOrders.test.jsx
[OEUI-81: Update the table display format for active and past orders](https://issues.openmrs.org/browse/OEUI-81)
This task basically meant to implement the feedback got from the community about the fields that should appear in Active and Past order tables
=> OEUI-81: Update the table display format for active and past orders

app/js/actions/settingEncounterRole.js, app/js/reducers/settingEncounterRoleReducer.js, tests/actions/settingEncounterRole.test.js
[OEUI-93: Check for order.encounterRole setting](https://issues.openmrs.org/browse/OEUI-93)
- Actions and Reducers to check if the setting for order.encounterRole exists.
- Conditional rendering of SearchAndAddOrder depending on the existence of the setting.
- Tests for the actions, reducers, and component.
=> OEUI-93: Check for the existance of the order.encounterRole setting (Bug Fix)

__mocks__/mockData.js, app/js/actions/encounterRole.js, app/js/actions/settingEncounterRole.js, app/js/components/orderEntry/OrderEntryPage.jsx, app/js/reducers/encounterRoleReducer.js, app/js/reducers/settingEncounterRoleReducer.js, tests/actions/encounterRole.test.js, tests/actions/settingEncounterRole.test.js, tests/components/orderentry/addForm/DraftDataTable.test.jsx, tests/reducers/encounterRoleReducer.test.js, tests/reducers/settingEncounterRoleReducer.test.js
[OEUI-100: Checking the existence of encounter type.](https://issues.openmrs.org/browse/OEUI-100)
This entails checking whether the encounter role whose name was set as a global property exists. If this encounter role does not exist then a user should get an error message on loading the drug order page.
This handle logic for validating proper and complete setup of the encounterRole configurations and notifies the user if not.
i.e `if return axiosInstance.get(encounterrole?q=${value})` is not successful, then an error is displayed like for *Configuration for encounterRole is incomplete*
=> OEUI-100: Checking the existence of encounter role

app/js/actions/encounterType.js, app/js/components/orderEntry/addForm/DraftDataTable.jsx
[OEUI-112: Fix Fix 'cannot execute statement' error when adding order.](https://issues.openmrs.org/browse/OEUI-112)
This is a bug fix for the bug in the encounterRole/encounterType action/reducer logic that results in a `cannot execute statement` error when trying to use the DraftTable component to add a new drug order.
=> OEUI-112: Fix 'cannot execute statement' error when adding order

app/js/actions/addDrugOrder.js, tests/actions/addDrugOrder.test.js
[OEUI-115: Bug fix to fetch past orders after an active order is edited or discontinued](https://issues.openmrs.org/browse/OEUI-115)
Currently, when an active order is edited or discontinued, the user would need to reload the page to see the order under the `Past Drug Orders` tab. This ticket is a bug fix to implement.
=> OEUI-115: Bug fix to fetch past orders after an active order is edited or discontinued

app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/SearchAndAddOrder.jsx, app/js/components/orderEntry/addForm/AddForm.jsx, app/js/reducers/activeOrderReducer.js
[OEUI-113: Bug fix for actions column when editing drug order](https://issues.openmrs.org/browse/OEUI-113)
This is a ticket to fix the behavior of the `actions` column icons changing to `will REVISE` in `Active Drug Orders` table when a new drug order is being added.
=> OEUI-113: Bug fix for actions column when editing drug order

package.json
[OEUI-110: Remove the second instance of tests run during Travis build](https://issues.openmrs.org/browse/OEUI-110)
Currently, Travis does not run tests, therefore master might have failing tests.
- Run tests and generate coverage report in Travis.
=> OEUI-110: Remove the second instance of tests run during Travis build (bug fix)

app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/PastOrders.jsx
[OEUI-121:  Show pagination only when orders are more than one page](https://issues.openmrs.org/browse/OEUI-121)
This ticket is based on feedback on [Talk](https://talk.openmrs.org/t/order-entry-ui-sprint-4-announcement/17921/76). It entails refactoring the pagination implementation to only show pagination when the orders are more the specified limit for a single page. That is, the pagination starts showing when orders spill into page 2 or more.
This implementation should be done for both active and past orders.
=> OEUI-121: Show pagination only when orders are more than one page

__mocks__/mockData.js, app/js/components/orderEntry/SearchAndAddOrder.jsx, app/js/components/orderEntry/addForm/DraftDataTable.jsx, app/js/components/orderEntry/addForm/FreeText.jsx, app/js/components/orderEntry/addForm/StandardDose.jsx, tests/components/orderentry/addForm/DraftDataTable.test.jsx
[OEUI-120: Change text to match implementation in existing omod](https://issues.openmrs.org/browse/OEUI-120)
This ticket is based on the feedback from [talk](https://talk.openmrs.org/t/order-entry-ui-sprint-4-announcement/17921/76). 
- Changes the text on the button clicked to add a draft order from Save to Add.
- Changes tab names from OutPatient to Outpatient, InPatient to Inpatient.
- Optimises draft order text and change Reason to As needed
=> OEUI-120: Change text to match implementation in existing omod

app/css/openmrs-owa-orderentry.css, app/js/components/orderEntry/addForm/DraftDataTable.jsx, tests/components/orderentry/addForm/DraftDataTable.test.jsx
[OEUI-123: Show details of order being discontinued.](https://issues.openmrs.org/browse/OEUI-123)
This ticket is based on feedback from Talk. When an active order is being discontinued, the entire details of the current order should be displayed for more context, not just the drug name.
=> OEUI-123: show details of order being discontinued

app/js/components/searchDrug/index.jsx, tests/components/searchDrug/index.test.jsx
[OEUI-129:  Populate new order for field when editing a drug order.](https://issues.openmrs.org/browse/OEUI-129)
When editing a new drug order, the new drug order for field is unpopulated. The field needs to be populated with the name of the drug order being edited.
=> OEUI-129: Populate new order for field when editing a drug order.

app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/addForm/DraftDataTable.jsx
[OEUI-128:  Correct tooltips with incorrect labels](https://issues.openmrs.org/browse/OEUI-128)
The wording for some tooltips does not correspond to what the buttons actually do.
Tooltip for edit draft drug order showing `delete` instead of `edit`.
Tooltip for discontinue draft drug order showing `delete` instead of `discontinue`
Plus any other tooltips that need to be corrected.
=> OEUI-128: Correct tooltips with incorrect labels

app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/PastOrder.jsx
[OEUI-125: Inconsistent date format on Order Entry display page](https://issues.openmrs.org/browse/OEUI-125)
The date format on the current order entry display page is inconsistent.  For Active orders it looks like it is using MM-DD-YYYY and for Past orders it is using DD-MM-YYYY.
These should be the same.  And since both of these formats could be confusing, especially when used by multiple countries following different conventions, I have used DD MMM YYYY, according to feedback.  That way, for example, the date will show as 6 May 2018 instead of 5-6-2018 or 6-5-2018.
=> OEUI-125: Inconsistent date format on Order Entry display page

app/js/components/orderEntry/addForm/AddForm.jsx, app/js/components/orderEntry/addForm/FreeText.jsx, app/js/components/orderEntry/addForm/StandardDose.jsx, tests/components/orderentry/addForm/AddForm.test.jsx, tests/components/orderentry/addForm/FreeText.test.jsx, tests/components/orderentry/addForm/StandardDose.test.jsx
[OEUI-117: Drop downs options should only be filtered by the first letter](https://issues.openmrs.org/browse/OEUI-117)
Currently on the dropdowns in the Order Entry UI when the user types any letter or combination of letters in any of combo boxes, the choices are filtered based on those letters appearing anywhere in the choices.    It would be better if the results were filtered based on those letters appearing in the beginning of the choices.  e.g. if a user types "ta" in the units box, they probably want tablet or tablespoon, but not container.
=> OEUI-117: Drop downs options should only be filtered by the first letter 

app/css/openmrs-owa-orderentry.css, app/js/components/orderEntry/addForm/FreeText.jsx, app/js/components/orderEntry/addForm/StandardDose.jsx
[OEUI-118: Widen drug prescription field boxes to accommodate available options.](https://issues.openmrs.org/browse/OEUI-118)
These text and combo boxes should be widened to accommodate the options...
- the text box at the top of the screen for the drug names should be widened.  e.g. some PIH implementations have a drug name as long as "acitracin 500 internatinal units/gram + neomycin sulphate 0.5 % (0.35 % base) skin-ointment, 15 gram tube".  It doesn't necessary need to be as long as this, but we should make it as long as we can on that page.
- The Dose and Dispensing Units box should be long enough for "International Units"
-  The Duration Units should be long enough for "number of occurrences"
There could still be issues, as the text in other languages may be longer, but we should …
=> OEUI-118: Widen drug prescription field boxes

app/css/openmrs-owa-orderentry.css, app/js/components/orderEntry/addForm/DraftDataTable.jsx, tests/components/orderentry/addForm/DraftDataTable.test.jsx
[OEUI-133: Deactivate edit icon (in the unsaved draft orders table) when discontinuing an active order](https://issues.openmrs.org/browse/OEUI-133)
When discontinuing an active order, an icon to edit (in the unsaved draft orders table) appears under the available actions. The icon makes the order to disappear when clicked. This edit icon should be deactivated.
=> OEUI-133: Deactivate edit icon (in the unsaved draft orders table) when discontinuing an active order

app/js/components/orderEntry/SearchAndAddOrder.jsx, app/js/components/orderEntry/addForm/AddForm.jsx, app/js/components/tabs/Tabs.jsx, tests/components/orderentry/SearchAndAddOrder.test.jsx, tests/components/orderentry/addForm/AddForm.test.jsx, tests/components/tabs/Tabs.test.js
[OEUI-126: Clear and close drug forms and unsaved draft orders table on switching between Inpatient and Outpatient tabs](https://issues.openmrs.org/browse/OEUI-126)
The Inpatient and Outpatient tabs on the Order Entry UI seem to share the same entry form.  By this I mean it is possible to switch between the two tabs as the user is filling out the form.  It is saved to Inpatient or Outpatient based on which tab is chosen when the user clicks save.  This can cause some confusion as there are different fields for the two tabs: e.g. The user may start in the Outpatient Tab, which includes dispensing units and then switch over to Inpatient and save, which would result in an Inpatient order with dispensing units filled out.  
It is also a little confusing during editing.  If you edit an …
=> OEUI-126: Clear and close drug forms and unsaved draft orders table on switching between Inpatient and Outpatient tabs

app/css/openmrs-owa-orderentry.css, app/js/components/orderEntry/ActiveOrders.jsx, app/js/components/orderEntry/PastOrders.jsx
[OEUI-139: Widen the date column to occupy only two row spans in Active and Past order tables](https://issues.openmrs.org/browse/OEUI-139)
In some instances, the dateStarted and dateStopped span three rows which is inconsistent. These dates should span only two columns.
=> OEUI-139: Widen the date column to occupy only two row spans in Active and Past order tables

__mocks__/mockData.js, app/js/components/orderEntry/PastOrder.jsx, tests/components/orderentry/PastOrder.test.jsx, tests/components/orderentry/PastOrders.test.jsx
[OEUI-132:  Past orders date should be dateActivated - dateStopped or autoExpireDate](https://issues.openmrs.org/browse/OEUI-132)
In the current implementation, discontinuing an active order places the order under past order with date in the format `dateCreated - autoExpireDate`. The date should be in the date format `dateActivated - dateStopped or autoExpireDate`. 
=> OEUI-132: Past orders date should be dateActivated - dateStopped or autoExpireDate

app/js/components/orderEntry/OrderEntryPage.jsx
[OEUI-131: Use a constant for the date format](https://issues.openmrs.org/browse/OEUI-131)
The date format that is sampled in the error message, when no global property has been added is currently incorrect. This PR fixes that, to show the correct intended date format.
=> OEUI-131: Use a constant for the date format (Bug Fix)

app/js/components/orderEntry/SearchAndAddOrder.jsx, app/js/components/orderEntry/addForm/AddForm.jsx, app/js/reducers/activeOrderReducer.js, tests/reducers/activeOrderReducer.test.js
[OEUI-156: Edit draft order bug fix](https://issues.openmrs.org/browse/OEUI-156)
This ticket fixes the bug that causes an order to be deleted when the edit button of an order on the unsaved draft orders table is clicked.
=> OEUI-156: Edit draft order bug fix

README.md
[OEUI-158: update readme](https://issues.openmrs.org/browse/OEUI-158)
This ticket fixes an incorrect response message for the npm run build:prod command.
PS: Update "This will create a file called openmrs-owa-orderentry.zip file in the dist directory..." to "This will create a file called openmrs-owa-orderentry.zip file in the root directory..."
Also adds more information to the readme
=> OEUI-158: update readme

app/js/actions/dateFormat.js, app/js/components/orderEntry/OrderEntryPage.jsx, tests/actions/dateFormat.test.js
[OEUI-160: Use a constant for the date format](https://issues.openmrs.org/browse/OEUI-160)
Currently, the app solely relies on the dateTime from the global config variable which results in an error if this is not already set in the app.
This PR adds a constant "DD-MMM-YYYY HH:mm" dateTime format as fallback incase the global dateTime is not configured.
=> OEUI-160: Add default dateTime format in app

app/js/components/orderEntry/OrderEntryPage.jsx, tests/components/orderentry/OrderEntryPage.test.jsx
[OEUI-159: Fix redirection issue in app](https://issues.openmrs.org/browse/OEUI-159)
This ticket fixes the redirection issue that causes the app to redirect to landing page when the user does not append a patient uuid to the url link.
**PS:** User should get an error rather than being redirected to the landing page like so
A valid patient uuid is required to view this page, please navigate to this page from the Clinician facing dashboard page or append a valid patient id "?patient=patient_uuid" to your url.
=> OEUI-159: Fix redirection issue in app

app/js/components/orderEntry/addForm/AddForm.jsx
[OEUI-162: Fix bug in standard/free text drug mode switch](https://issues.openmrs.org/browse/OEUI-162)
This ticket fixes the bug that occurs when a user switches between to the free text drug entry mode from the standard mode causing the "Add" button to be disabled.
NOTE: This happens when the user has an error on some of the fields in the standard mode and switches to the free text mode. See image below
=> OEUI-162: Fix bug in standard/free text drug mode switch

jest.config.js
[OEUI-171: Make component snapshots readable](https://issues.openmrs.org/browse/OEUI-171)
The snapshots generated from the snapshot tests are not readable and this makes it difficult to know if the snapshot generated is actually what is expected(the real essence of the snapshot). This Pull Request adds a serializer that ensures that the snapshots are readable.
=> OEUI-171: Make component snapshots readable

app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/PastOrders.jsx, package.json, tests/components/labOrderEntry/LabEntryForm.test.jsx
[OEUI-210: Moment vs date-fns](https://issues.openmrs.org/browse/OEUI-210)
This Pull Request replaces the use of `Moment.js` date library with `Date-fns.js` in the code base.
=> OEUI-210: Replace Moment.js with Date-fns.js

app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/LabTestFieldSet.jsx, app/js/components/labOrderEntry/styles.scss, app/js/reducers/initialState.js, app/js/reducers/labOrders/labConceptsReducer.js, tests/components/labOrderEntry/LabEntryForm.test.jsx, tests/components/labOrderEntry/LabTestFieldSet.test.jsx, tests/reducers/labOrderReducers/labConceptsReducer.test.js
[OEUI-205: Render the lab-tests belonging to a lab category](https://issues.openmrs.org/browse/OEUI-205)
This Pull Request renders the Lab Tests dynamically with the data gotten from the database replacing the mock data used previously.  
**NOTE:** This pull request actually breaks the functionality of adding panels to draft and that is because of the change in the data model. However, this issue would be fixed in this [JIRA TICKET](https://issues.openmrs.org/browse/OEUI-212)
=> OEUI-205: Render Lab Tests dynamically

app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/LabPanelFieldSet.jsx, app/js/components/labOrderEntry/styles.scss, app/js/reducers/initialState.js, app/js/reducers/labOrders/labConceptsReducer.js, tests/components/labOrderEntry/LabEntryForm.test.jsx, tests/components/labOrderEntry/LabPanelFieldSet.test.jsx, tests/reducers/labOrderReducers/labConceptsReducer.test.js
[OEUI-200: Render the concepts of type LabSet as the panels belonging to a Lab Category](https://issues.openmrs.org/browse/OEUI-200)
This Pull Request renders the Test Panels dynamically with the data gotten from the database replacing the mock data used previously.  
**NOTE:** This pull request actually breaks the functionality of adding panels to draft and that is because of the change in the data model. However, this issue would be fixed in this [JIRA TICKET](https://issues.openmrs.org/browse/OEUI-212)
=> OEUI-200: Render Test Panels dynamically

app/js/components/labOrderEntry/LabDraftOrder.jsx, app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/styles.scss, app/js/reducers/draftLabOrderReducer.js, app/js/reducers/labOrders/labConceptsReducer.js, tests/components/labOrderEntry/LabDraftOrder.test.jsx, tests/components/labOrderEntry/LabEntryForm.test.jsx, tests/reducers/draftLabOrderReducer.test.js
[OEUI-212: Update the add-to-draft logic for test and panels](https://issues.openmrs.org/browse/OEUI-212)
Due to the change in data model when we switched from dummy-data to real data for test and panels, the add-to/remove-from daft functionality was breaking, this Pull Request ensures that both functionalities are working fine.
=> OEUI-212: Update add/remove to/from draft logic

app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/LabPanelFieldSet.jsx, app/js/components/labOrderEntry/LabTestFieldSet.jsx, app/js/components/labOrderEntry/styles.scss, app/js/reducers/draftLabOrderReducer.js, app/js/reducers/labOrders/labConceptsReducer.js, tests/reducers/labOrderReducers/labConceptsReducer.test.js
[OEUI-219: Only tests that are top-level should be orderable.](https://issues.openmrs.org/browse/OEUI-219)
In the previous implementation of panel/test selection when making Lab Order, any test in the tests-box can be selected regardless of if it is a standalone test or not. This pull request removes all the test that are not standalone from the tests-box consequently making only standalone tests orderable.
=> OEUI-219: Make Only Top level Lab-Tests Orderable

app/js/components/drugOrderEntry/styles.scss, app/js/components/labOrderEntry/LabPanelFieldSet.jsx, app/js/components/labOrderEntry/TestsToolTip.jsx, app/js/components/labOrderEntry/styles.scss, tests/components/labOrderEntry/TestsToolTip.test.jsx
[OEUI-223: Display all the lab-tests associated to a lab-panel in a tool-tip.](https://issues.openmrs.org/browse/OEUI-223)
A Lab-panel has a lot of Lab-tests associated with it, however, this is not evident/obvious from the current user interface of the application. This pull request displays all the Lab-tests associated with a Lab-panel in a ToolTip just above the Panel button when it is hovered.
=> OEUI-223: Display lab panel-tests in a tool-tip

app/js/components/labOrderEntry/LabDraftOrder.jsx, app/js/components/labOrderEntry/styles.scss
[OEUI-249](https://issues.openmrs.org/browse/OEUI-249) Change urgency Icon
- This PR updates the urgency Icon to use a triangle without exclamation mouse
=> OEUI-249: Change urgency Icon

app/css/openmrs-owa-orderentry.scss, app/js/components/Draft.jsx, app/js/components/drugOrderEntry/addForm/FreeText.jsx, app/js/components/drugOrderEntry/addForm/StandardDose.jsx, app/js/components/drugOrderEntry/index.jsx, app/js/components/drugOrderEntry/styles.scss, app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/labOrderEntry/styles.scss, app/js/components/orderEntry/OrderEntryPage.jsx, app/js/components/orderEntry/RenderOrderType.jsx, app/js/components/orderEntry/styles.scss, tests/components/Draft.test.jsx, tests/components/labOrderEntry/LabEntryForm.test.jsx, tests/components/orderentry/OrderEntryPage.test.jsx
[OEUI-232: Make a Draft order component reusable in all order page](https://issues.openmrs.org/browse/OEUI-232)
- This should make a Draft order component reusable and visible in all order page.
=> OEUI-232: Make draft order list reuseable on all pages

app/js/actions/draftActions.js, app/js/actions/draftLabOrderAction.js, app/js/components/Draft.jsx, app/js/components/labOrderEntry/LabEntryForm.jsx, app/js/components/orderEntry/OrderEntryPage.jsx, tests/actions/draftActions.test.js, tests/actions/draftLabOrderAction.test.js, tests/components/Draft.test.jsx, tests/components/labOrderEntry/LabEntryForm.test.jsx, tests/components/orderentry/OrderEntryPage.test.jsx
[OEUI-238: User should be able to toggle the urgency of a lab order from the draft.](https://issues.openmrs.org/browse/OEUI-238)
This pull request adds the functionality that enables users to toggle the urgency of Lab Orders from the new shared draft.
=> OEUI-238: Toggle lab urgency from shared draft

app/js/actions/draftActions.js, app/js/components/Draft.jsx, app/js/components/button/IconButton.jsx, app/js/components/orderEntry/OrderEntryPage.jsx, tests/actions/draftActions.test.js
[OEUI-239](https://issues.openmrs.org/browse/OEUI-239)
- Users who add a drug or lab order should be able to discard the item.
=> OEUI-239: User should be able to discard a lab order from the draft list

app/js/actions/draftActions.js, app/js/actions/draftTableAction.js, app/js/components/Draft.jsx, tests/actions/draftActions.test.js, tests/actions/draftTableAction.test.js
[OEUI-237: Discard a drug order from the draft list](https://issues.openmrs.org/browse/OEUI-237)
- Users who adds a drug order should be able to discard the item from the draft list when the "X" button is clicked
=> OEUI-237: Discard a drug order from the draft list

app/js/components/drugOrderEntry/addForm/AddForm.jsx, app/js/reducers/addDrugOrderReducer.js, app/js/utils/errorMessages.json, tests/components/DrugOrderEntry/addForm/AddForm.test.jsx, tests/reducers/addDrugOrderReducer.test.js
[OEUI-247](https://issues.openmrs.org/browse/OEUI-247)
-  Use toast messages to display server messages when creating a drug order.
=> OEUI-247: Implement Toast Message When Creating Drug Order

app/js/components/orderEntry/RenderOrderType.jsx, app/js/components/orderEntry/orderTypes.js, app/js/components/orderEntry/styles.scss, tests/components/orderentry/RenderOrderType.test.jsx, tests/components/orderentry/SelectOrderType.test.jsx
[OEUI-263 Add order from sets to order types ](https://issues.openmrs.org/browse/OEUI-263)
- Add order from sets to order types so that it displays in order type drop-down
=> OEUI-263: Add order from set to order types

app/js/components/orderEntry/Paginate.jsx, app/js/components/orderEntry/styles.scss, tests/components/orderentry/Paginate.test.jsx
[OEUI-279 Order List page number showing as "NaN"](https://issues.openmrs.org/browse/OEUI-279) 
- Fix Order list pagination showing NAN
- Disable the previous button if the total order is less than ten.
=> OEUI-279: Fix order list pagination showing NAN

app/js/components/orderEntry/OrdersTable.jsx, tests/components/orderentry/OrdersTable.test.jsx
[OEUI-282: (New) and (Revise) should not appear on order list](https://issues.openmrs.org/browse/OEUI-282)
- Remove (New) and (Revise) from the order list
- New and Revise should show on draft list
=> OEUI-282: (New) and (Revise) should not appear on order list

app/js/components/orderEntry/OrderHeader.jsx, app/js/components/orderEntry/OrdersTable.jsx, tests/components/orderentry/OrdersTable.test.jsx
[OEUI-281 Allow discontinue of Test Order from the order list](https://issues.openmrs.org/browse/OEUI-281)
- On the Order List page, for drugs user can discontinue or edit orders.
- Users should be able to discontinue test orders.
=> OEUI-281: Allow discontinue of Test Order from the order list

README.md, app/index.html, package.json, webpack.config.js
[OEUI-278: Rename Order Entry app from "openmrs-owa-orderentry" to "orderentry" ](https://issues.openmrs.org/browse/OEUI-278)
- I renamed the app from "openmrs-owa-orderentry" to "orderentry" 
- The deployed artefact was changed from "openmrs-owa-orderentry.zip" to "orderentry.zip" 
- The title of the index.html file was changed to `orderentry`
- The package.json name was changed to `orderentry`
- The weback.config.js, config.json and package.json were edited accordingly.
=> OEUI-278: Rename Order Entry app from "openmrs-owa-orderentry" to "orderentry"

app/js/components/setsOrderEntry/OrderSetForm.jsx, tests/components/setOrderEntry/OrderSetForm.test.jsx
[OEUI-269: Cancel Order Set Action](https://issues.openmrs.org/browse/OEUI-269)
- When the cancel button is clicked, user should be returned to the select dropdown view
- The edit and delete action buttons should also be removed
=> OEUI-269: Cancel Order Set Action

app/js/components/orderEntry/styles.scss
[OEUI-288: Extend secondary header on the page](https://issues.openmrs.org/browse/OEUI-288)
- The white space does not extend to the edge of the usable space on the page. This PR aim was to fix the issue.
=> OEUI-288: Extend secondary header on the page

app/js/actions/createOrder.js, app/js/components/orderEntry/OrderEntryPage.jsx, app/js/middlewares/responseHandlerMiddleware.js, app/js/reducers/initialState.js, tests/components/orderentry/OrderEntryPage.test.jsx, tests/middlewares/responseHandlerMiddleware.test.js
[UHM-3495](https://tickets.pih-emr.org/browse/UHM-3495)
[OEUI-294](https://issues.openmrs.org/browse/OEUI-294)
- This PR allows you open the app in either lab orders page or drug order page. it also allows you set a return URL when you sign or save draft orders
?patient=da5e210f-a3c4-4c49-80f2-e2e5386db8ad&page=Lab%20Orders&returnurl=https://www.google.com/#
just add a `page` and `returnurl` as part of the query string.
- [x ] I can sucessfully create Drug orders
- [x ] I can sucessfully create Lab orders
- [x ] I can sucessfully search for drug orders
=> UHM-5495 and OEUI-294 : Stand alone lab order flow

.gitignore, app/js/components/drugOrderEntry/addForm/AddForm.jsx
[OEUI-291: Fix Bug in Edit drug order functionality](https://issues.openmrs.org/browse/OEUI-291) 
- Added **activity** condition to check if `activity === "EDIT"` hence proceed to edit.
=> OEUI-291: Fix Bug in Edit drug order functionality

app/js/components/orderEntry/OrderEntryPage.jsx, app/js/components/orderEntry/RenderOrderType.jsx
[OEUI-293: Enforce prop-type validation in all components](https://issues.openmrs.org/browse/OEUI-293)
- Some components do not have prop-type validation present, the goal of this ticket is to locate such components and add prop-type validations.
=> OEUI-293: Enforce prop-type validation in all components

app/js/components/orderEntry/OrderEntryPage.jsx
[UHM-3495](https://tickets.pih-emr.org/browse/UHM-3495)
[OEUI-294](https://issues.openmrs.org/browse/OEUI-294)
- This PR hides the menu that allows users to switch to drug orders when you navigate to the page from the patient-dashboard
=> UHM-3495: Hide selectOrderTypes

.gitignore, app/js/components/orderEntry/RenderOrderType.jsx, package-lock.json
[OEUI-297: Fix PropTypes import error OrderEntryPage.jsx file](https://issues.openmrs.org/browse/OEUI-297) 
- Fixed by imorting `PropTypes` in the `OrderEntryPage` component.
=> OEUI-297: Fix PropTypes import error OrderEntryPage.jsx file

app/index.html
[OEUI-300](https://issues.openmrs.org/browse/OEUI-300) Browser Tab Heading/Title should read "OpenMRS Electronic Medical Record"
- changed app title from orderentry to OpenMRS Electronic Medical Record
=> OEUI-300: Browser Tab Heading/Title should read "OpenMRS Electronic Medical Record"

app/js/actions/createOrder.js, app/js/components/orderEntry/OrderEntryPage.jsx, app/js/components/orderEntry/SelectOrderType.jsx, app/js/middlewares/responseHandlerMiddleware.js
[OEUI-302](https://issues.openmrs.org/browse/OEUI-302) Tweak layout of "Add Order" button when restricting to a single order type
- Tweak layout of "Add Order" button when restricting to a single order type
=> OEUI-302: Tweak layout of "Add Order" button when restricting to a single order type

app/js/components/orderEntry/OrderEntryPage.jsx, app/js/reducers/initialState.js, app/js/reducers/patientReducer.js, tests/components/orderentry/OrderEntryPage.test.jsx, webpack.config.js
[UHM-3845](https://tickets.pih-emr.org/browse/UHM-3845) Empty Strings in Patient Header
- Fix for Patient Header on Order Entry UI page does not display patient identifier
=> UHM-3845: removed defaultPatient object in initialState

app/js/components/orderEntry/OrderHeader.jsx, tests/components/orderentry/OrderHeader.test.jsx
The edit and cancel buttons didn't work out of the box for drug orders, and we're not going to fix them right now, so we're disabling them altogether for now.
=> Remove edit and cancel buttons from drug orders
