openmrs/openmrs-owa-orderentry

- app/index.html
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/tabs/Tab.jsx
- app/js/components/tabs/Tabs.jsx
- tests/components/orderentry/__snapshots__/SearchAndAddOrder.test.jsx.snap
- tests/components/patientDashboard/__snapshots__/View.test.jsx.snap
- tests/components/patientDashboard/__snapshots__/index.test.jsx.snap
- tests/components/tabs/Tab.test.js
- tests/components/tabs/Tabs.test.js
- tests/components/tabs/__snapshots__/Tab.test.js.snap
- tests/components/tabs/__snapshots__/Tabs.test.js.snap
[OEUI-49: Implement Tab functionality](https://issues.openmrs.org/browse/OEUI-49)
Implement the tab functionality for switching between patient's careSettings that is `outpatient` and `inpatient`.
> OEUI-49: Implement Tab functionality

- app/js/components/patientDashboard/index.jsx
- tests/components/patientDashboard/index.test.jsx
[OEUI-41: Patient Information and OpenMRS Navbar Integration](https://issues.openmrs.org/browse/OEUI-41) (Update)
Integrate the current OpenMRS navigation bar and patient information into the order entry standalone OWA app.
> OEUI-41: Patient Information and OpenMRS Navbar (With bug fix)

- app/js/components/patientDashboard/View.jsx
[OEUI-41: Patient Information and OpenMRS Navbar Integration](https://issues.openmrs.org/browse/OEUI-41) (Bug Fix)
Fix bug with the `Edit` links for updating patient's information.
> OEUI-41: Patient Information and OpenMRS Navbar (Bug fix)

- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
- app/js/components/orderEntry/addForm/FreeText.jsx
- tests/components/orderentry/SearchAndAddOrder.test.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
- tests/components/orderentry/addForm/DraftDataTable.test.jsx
- tests/components/orderentry/addForm/FreeText.test.jsx
[OEUI-60: Confirm post/put drug order implementation](https://issues.openmrs.org/projects/OEUI/issues/OEUI-60)
This includes an implementation of a table that displays the draft data from both standard dosing form and free text form. This enables users to view whatever they have filled in the forms and confirm that they actually want to make a post or put a request for a drug order to the API.
> OEUI-60: Confirm post/put drug order implementation

- app/js/components/orderEntry/PastOrder.jsx
- app/js/components/orderEntry/PastOrders.jsx
- app/js/components/orderEntry/SearchAndAddOrder.jsx
[OEUI-37:Consume Api to show all past orders](https://issues.openmrs.org/browse/OEUI-37)
Show past orders for both in-patient and out-patient tabs
> OEUI-37: Consume Api to show all past orders(bug fix)

- tests/actions/activeOrderAction.test.js
- tests/actions/addDrugOrder.test.js
- tests/actions/drug.test.js
- tests/actions/encounterType.test.js
- tests/actions/header.test.js
- tests/actions/orderEntryActions.test.js
- tests/actions/pastOrders.test.js
- tests/actions/patient.test.js
- tests/route.test.js
- tests/setup.js
[OEUI-68: Optimising action's tests](https://issues.openmrs.org/browse/OEUI-68)
This includes adding packages that have been called in each action's test file to the global setup, reducing data duplication in individual files.
> OEUI-68: Optimising action's test

- tests/components/accordion/index.test.jsx
- tests/components/breadCrumb/index.test.jsx
- tests/components/header/View.test.jsx
- tests/components/header/index.test.jsx
- tests/components/orderentry/ActiveOrders.test.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/components/orderentry/PastOrders.test.jsx
- tests/components/orderentry/SearchAndAddOrder.test.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
- tests/components/orderentry/addForm/FreeText.test.jsx
- tests/components/orderentry/addForm/StandardDose.test.jsx
- tests/components/patientDashboard/View.test.jsx
- tests/components/patientDashboard/index.test.jsx
- tests/components/searchDrug/View.test.jsx
- tests/components/searchDrug/index.test.jsx
- tests/components/tabs/Tab.test.js
- tests/components/tabs/Tabs.test.js
- tests/setup.js
[OEUI-73: Optimising components' tests](https://issues.openmrs.org/browse/OEUI-73)
This includes adding packages that have been called in each component's test file to the global setup, reducing data duplication in individual files.
> OEUI-73: Optmising components' tests

- .gitignore
- app/js/components/orderEntry/PastOrders.jsx
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/FreeText.jsx
- app/js/components/tabs/DosageTab.jsx
- app/js/components/tabs/DosageTabs.jsx
- tests/components/tabs/DosageTab.test.js
- tests/components/tabs/DosageTabs.test.js
[OEUI-58:Implement tab functionality for standard dosing and free text](https://issues.openmrs.org/browse/OEUI-58)
This entails enabling a user to either choose standard dosing or free text format of adding instructions when adding a new drug order or editing active drug order. This also includes updating the store on which format the user is using.
> OEUI-58: Implement tab functionality for standard dosing and free text

- tests/reducers/activeOrderReducer.test.js
- tests/reducers/drugSearchReducer.test.js
- tests/reducers/encounterReducer.test.js
- tests/reducers/locationReducer.test.js
- tests/reducers/noteReducer.test.js
- tests/reducers/orderEntryReducer.test.js
- tests/reducers/pastOrdersReducer.test.js
- tests/reducers/patientReducer.test.js
- tests/reducers/sessionReducer.test.js
[OEUI-74: Optimising reducers' tests](https://issues.openmrs.org/browse/OEUI-74)
This includes adding packages that have been called in each reducers's test file to the global setup, reducing data duplication in individual files.
> OEUI-74: Optimising reducers' tests

- app/js/actions/loading.js
[OEUI-67: Create a generic loader](https://issues.openmrs.org/browse/OEUI-67)
This includes implementing a generic loader action that accepts dynamic action types and can be used throughout the application. For example, instead of creating a different loader action for active order and another for past order, one could use the generic loader and supply a different action type in each case.
> OEUI-67: Create a generic loader

- app/js/components/orderEntry/PastOrders.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/tabs/DosageTab.jsx
- app/js/components/tabs/DosageTabs.jsx
- tests/components/tabs/DosageTab.test.js
- tests/components/tabs/DosageTabs.test.js
[OEUI-58:Implement tab functionality for standard dosing and free text](https://issues.openmrs.org/browse/OEUI-58)
This entails enabling a user to either choose standard dosing or free text format of adding instructions when adding a new drug order or editing active drug order. This also includes updating the store on which format the user is using.
> OEUI-58: Implement tab functionality for standard dosing and free text(code optimization)

- app/css/grid.scss
- app/css/openmrs-owa-orderentry.css
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
- app/js/components/orderEntry/addForm/FreeText.jsx
- app/js/components/orderEntry/addForm/StandardDose.jsx
- app/js/components/tabs/Tabs.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
- tests/components/orderentry/addForm/StandardDose.test.jsx
- tests/components/searchDrug/index.test.jsx
[OEUI-62: Standard dosing form validations](https://issues.openmrs.org/browse/OEUI-62)
This includes the following:
- Validations for standard dose form fields.
- Tests for standard dose form.
- Refactoring standard dose UI based on feedback.
> OEUI-62: Standard dosing form validations

- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
[OEUI-77: Bug fix for confirm post/put drug order implementation](https://issues.openmrs.org/projects/OEUI/issues/OEUI-77)
This includes:
- Adding spaces to between values in the table.
- Using the same state for the textarea in both standard dosing
and free text forms.
- Updating the title Unsaved Draft Data to Unsaved Draft Orders.
- Updating the button label Confirm Save to Sign and Save.
- Allow addition of many orders at ago and display all those orders
in the Unsaved Draft Orders table.
- Edit one draft order.
- Delete one draft order.
- Discarding all draft orders.
> OEUI-77: Bug fix for confirm post/put drug order implementation (bug fix)

- app/js/components/patientDashboard/View.jsx
[OEUI-89: Fix bug in patient dashboard causing app to crash.](https://issues.openmrs.org/browse/OEUI-89)
Fix bug in patient dashboard causing app to crash when `show contact info` link is clicked.
> OEUI-89: Fix bug in patient dashboard causing app to crash

- app/js/actions/activeOrderAction.js
- app/js/actions/addDrugOrder.js
- app/js/actions/careSetting.js
- app/js/actions/discontinueOrder.js
- app/js/actions/drug.js
- app/js/actions/encounterType.js
- app/js/actions/header.js
- app/js/actions/orderEntryActions.js
- app/js/actions/pastOrders.js
- app/js/actions/patient.js
- app/js/actions/settingEncounterType.js
- app/js/config.js
- tests/setup.js
[OEUI-91: Implement axios instance in all previously implemented actions](https://issues.openmrs.org/browse/OEUI-91)
This ticket will require the creation of a config file that will create an axios instance and set the baseURL. The task would also require changing all the previous api calls to use the axios instance
> OEUI-91: Implement axios instance in all previously implemented actions

- app/js/actions/careSetting.js
- app/js/actions/encounterType.js
- app/js/actions/orderEntryActions.js
- app/js/actions/settingEncounterType.js
- tests/actions/encounterType.test.js
- tests/actions/orderEntryActions.test.js
- tests/actions/settingEncounterType.test.js
- tests/reducers/orderEntryReducer.test.js
- tests/reducers/settingEncounterTypeReducer.test.js
[OEUI-84:  Integrate generic loader for careSettings, encounterType, orderEntryActions and settingEncounterType](https://issues.openmrs.org/browse/OEUI-84)
This ticket implements integration of generic loader for careSetting, encounterType, orderEntryActions and settingEncounterType actions.
> OEUI-84: Integrate generic loader for careSettings, encounterType, orderEntryActions and settingEncounterType

- app/js/components/orderEntry/ActiveOrders.jsx
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- tests/components/orderentry/SearchAndAddOrder.test.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
[OEUI-54: Display populated edit form](https://issues.openmrs.org/browse/OEUI-54)
This involves displaying populated the edit form when one clicks on the edit button of an active drug order.
> OEUI-54: Display populated edit forms.

- __mocks__/mockData.js
- app/css/openmrs-owa-orderentry.css
- app/js/actions/encounterType.js
- app/js/actions/settingEncounterRole.js
- app/js/actions/settingEncounterType.js
- app/js/components/orderEntry/OrderEntryPage.jsx
- app/js/config.js
- tests/actions/encounterType.test.js
- tests/actions/settingEncounterType.test.js
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/reducers/settingEncounterTypeReducer.test.js
[OEUI-94: Checking the existence of encounter type.](https://issues.openmrs.org/browse/OEUI-94)
This entails checking whether the encounter type whose name was set as a global property exists. If this encounter type does not exist then a user should get an error message on loading the drug order page.
This handle logic for validating proper and complete setup of the encounterType configurations and notifies the user if not.
i.e `if return axiosInstance.get(encountertype?q=${value})` is not successful, then an error is displayed like for *Configuration for encounterType is incomplete*
> OEUI-94: Checking the existence of encounter type

- .eslintrc
- app/js/components/header/View.jsx
- app/js/components/orderEntry/ActiveOrders.jsx
- app/js/components/orderEntry/OrderEntryPage.jsx
- app/js/components/orderEntry/PastOrder.jsx
- app/js/components/orderEntry/PastOrders.jsx
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/tabs/DosageTab.jsx
- app/js/components/tabs/DosageTabs.jsx
- app/js/components/tabs/Tabs.jsx
- app/js/redux-store.jsx
- package.json
[OEUI-98: Fix Linter and prop type validation issues](https://issues.openmrs.org/browse/OEUI-98)
- Add missing prop type validations.
- Correct invalid prop type validations.
- Fix linter errors and warning.
> OEUI-98: Fix linter and prop type validation issues

- __mocks__/mockData.js
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
- app/js/components/orderEntry/addForm/FreeText.jsx
- app/js/components/orderEntry/addForm/StandardDose.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
[OEUI-102: Re-implement edit drug draft order](https://issues.openmrs.org/browse/OEUI-102)
This involves handling edit of a draft order. This resulted from the optimization of the draft data table which made the previous handle edit function obsolete.
> OEUI-102: Re-implement edit drug draft order.

- app/js/components/orderEntry/ActiveOrders.jsx
[OEUI-87: Front End Implement Pagination for Active Orders](https://issues.openmrs.org/browse/OEUI-87)
This ticket will involve frontend implementation of pagination for active and past orders in ReactJs
> OEUI-87: Front End Implement Pagination for Active Orders(Bug Fix)

- app/js/reducers/activeOrderReducer.js
- app/js/reducers/careSettingReducer.js
- app/js/reducers/discontinueOrderReducer.js
- app/js/reducers/draftTableReducer.js
- app/js/reducers/drugSearchReducer.js
- app/js/reducers/encounterReducer.js
- app/js/reducers/encounterRoleReducer.js
- app/js/reducers/initialState.js
- app/js/reducers/locationReducer.js
- app/js/reducers/noteReducer.js
- app/js/reducers/pastOrdersReducer.js
- app/js/reducers/patientReducer.js
- app/js/reducers/sessionReducer.js
- app/js/reducers/settingEncounterRoleReducer.js
- app/js/reducers/settingEncounterTypeReducer.js
[OEUI-103:  Optimize app to use initial state implementation for reducers](https://issues.openmrs.org/browse/OEUI-103)
This ticket is a code optimization for implementation of initial state for all reducers used in the app.
> OEUI-103: Optimize app to use initial state implementation for reducers

- __mocks__/mockData.js
- app/js/actions/addDrugOrder.js
- app/js/actions/encounterRole.js
- app/js/components/orderEntry/SearchAndAddOrder.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
- app/js/openmrs-owa-orderentry.jsx
- app/js/reducers/addDrugOrderReducer.js
- app/js/reducers/encounterReducer.js
- app/js/reducers/index.js
- app/js/reducers/sessionReducer.js
- package.json
- tests/actions/addDrugOrder.test.js
- tests/components/orderentry/addForm/DraftDataTable.test.jsx
- tests/reducers/addDrugOrderReducer.test.js
- tests/reducers/encounterReducer.test.js
[OEUI-76: Make a POST request to actually add orders.](https://issues.openmrs.org/browse/OEUI-76)
This includes working on the handleSubmit method to allow a user to add multiple orders after clicking the confirm save button. It includes making a payload that contains encounter details, provider, location, patient's information, obs if present, a list of orders and other necessary values.
> OEUI-76: Make a POST request to actually add orders.

- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
[OEUI-111: Save edited drug order](https://issues.openmrs.org/browse/OEUI-111)
This ticket involves finally saving the newly edited drug order by clicking the Sign and save button.
> OEUI-111: Save edited drug order

- tests/reducers/activeOrderReducer.test.js
- tests/reducers/careSettingReducer.test.js
- tests/reducers/drugSearchReducer.test.js
- tests/reducers/orderEntryReducer.test.js
- tests/reducers/pastOrdersReducer.test.js
- tests/reducers/sessionReducer.test.js
- tests/reducers/settingEncounterRoleReducer.test.js
[OEUI-108: Update reducer test files to improve on the codebase test coverage](https://issues.openmrs.org/browse/OEUI-108)
This task will involve updating the reducer test files to improve the overall reducers test coverage.
> OEUI-108: Update reducer test files to improve on the codebase test coverage

- tests/components/searchDrug/index.test.jsx
[OEUI-104: Bug fix for failing app test file](https://issues.openmrs.org/browse/OEUI-104)
This ticket is a bug fix to resolve the issues that occurred in `index.test.js` which resulted in the app tests failing on Travis..
> OEUI-104 Bug fix for failing app test file

- app/js/components/orderEntry/SearchAndAddOrder.jsx
[OEUI-102: Re-implement edit drug draft order](https://issues.openmrs.org/browse/OEUI-102)
This involves handling edit of a draft order. This resulted from the optimization of the draft data table which made the previous handle edit function obsolete.
> OEUI-102: Re-implement edit drug draft order (bug fix)

- __mocks__/mockData.js
- app/js/components/orderEntry/ActiveOrders.jsx
- app/js/components/orderEntry/PastOrders.jsx
- app/js/components/orderEntry/addForm/AddForm.jsx
- app/js/components/orderEntry/addForm/DraftDataTable.jsx
- tests/components/orderentry/ActiveOrders.test.jsx
- tests/components/orderentry/PastOrder.test.jsx
- tests/components/orderentry/PastOrders.test.jsx
- tests/components/orderentry/SearchAndAddOrder.test.jsx
- tests/components/orderentry/addForm/AddForm.test.jsx
- tests/components/orderentry/addForm/DraftDataTable.test.jsx
- tests/components/patientDashboard/View.test.jsx
- tests/components/tabs/DosageTab.test.js
- tests/components/tabs/DosageTabs.test.js
[OEUI-109:Update component test files to improve on the codebase test coverage](https://issues.openmrs.org/browse/OEUI-109)
This task will involve updating the component test files to improve the overall components test coverage.
> OEUI-109: Update component test files to improve on the codebase test coverage

- app/js/reducers/activeOrderReducer.js
- tests/reducers/activeOrderReducer.test.js
[OEUI-127: Fix failing tests.](https://issues.openmrs.org/browse/OEUI-127)
Fixing failing tests after the last merge on master.
> OEUI-127: Fix failing tests

- app/js/actions/activeOrderAction.js
- app/js/actions/pastOrders.js
- app/js/components/orderEntry/ActiveOrders.jsx
- app/js/components/orderEntry/PastOrders.jsx
- tests/actions/activeOrderAction.test.js
- tests/actions/pastOrders.test.js
[OEUI-101:  Drug orders arrangement - most recent drug orders first](https://issues.openmrs.org/browse/OEUI-101)
This ticket involves arranging the active orders to show the most recent active drug orders  at the top in `Active Drug Orders` section. Also, show the most recently stopped drug orders at the top in `Past Drug Orders` section.
> OEUI-101: Drug orders arrangement - most recent drug orders first

- .travis.yml
- bintray.json
[OEUI-143: Roll out a beta release](https://issues.openmrs.org/browse/OEUI-143)
Setup dependencies for a beta release roll out of the Order Entry UI application for testing.
> OEUI-143: Roll out a beta release

- .travis.yml
[OEUI-143: Roll out a beta release](https://issues.openmrs.org/browse/OEUI-143) - Improvement
Setup dependencies for a beta release roll out of the Order Entry UI application for testing.
Update travis.yml user
> OEUI-143: Setup dependecies for release app on bintray (#97)

- app/js/components/orderEntry/OrderEntryPage.jsx
[OEUI-155: Update configuration error messages](https://issues.openmrs.org/browse/OEUI-155)
This ticket updates the error messages for encounter role and encounter type global configs.
As pointed out by Daniel Kayiwa.
> OEUI-155: Update configuration error messages

- app/js/components/orderEntry/OrderEntryPage.jsx
[OEUI-157: Fix bug in encounter configs](https://issues.openmrs.org/browse/OEUI-157)
This ticket fixes the bugs in encounterRole and encounterType global configs that results in an error when the values is empty
> OEUI-157: Fix bug in encounter configs

- README.md
- app/js/actions/settingEncounterRole.js
- app/js/actions/settingEncounterType.js
- app/js/components/orderEntry/OrderEntryPage.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
[OEUI-163: Make dateTimeFormat key consistent with others](https://issues.openmrs.org/browse/OEUI-163)
This ticket updates the config namespace used all through the app to from order to orderentryowa.
This is to maintain consistency with the dateAndTimeFormat config and also provide a better distinction to the order entry ui configs in the global config.
> OEUI-163: Update global configs namespace

- app/css/openmrs-owa-orderentry.css
- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/labOrderEntry/LabPanelFieldSet.jsx
- app/js/components/labOrderEntry/LabTestFieldSet.jsx
- app/js/components/labOrderEntry/labData.js
- app/js/components/orderEntry/RenderOrderType.jsx
- jest.config.js
- tests/components/labOrderEntry/LabEntryForm.test.jsx
- tests/components/labOrderEntry/LabPanelFieldSet.test.jsx
- tests/components/labOrderEntry/LabTestFieldSet.test.jsx
[OEUI-168: add lab order entry form](https://issues.openmrs.org/browse/OEUI-168)
Add a lab order entry form that shows the categories as well as the panels and tests slated for that category.
when a panel is selected the tests should be automatically selected as well but can be deselected at the user's discretion.
> OEUI-168: add lab order entry form

- app/css/openmrs-owa-orderentry.css
- app/js/components/accordion/index.jsx
- app/js/components/labOrderEntry/ActiveOrders.jsx
- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/labOrderEntry/PastOrders.jsx
- app/js/components/labOrderEntry/ordersHistoryMockData.js
- tests/components/labOrderEntry/activeOrders.test.jsx
- tests/components/labOrderEntry/pastOrders.test.jsx
[Create Components For Lab Order History](https://issues.openmrs.org/browse/OEUI-173)
- Build out Past and Active Lab order History section with React
> OEUI-173: Create Components For Lab Order History

- __mocks__/mockData.js
- app/js/components/drugOrderEntry/addForm/DraftDataTable.jsx
- app/js/reducers/dateFormatReducer.js
- tests/components/DrugOrderEntry/ActiveOrders.test.jsx
- tests/components/DrugOrderEntry/PastOrder.test.jsx
- tests/components/DrugOrderEntry/PastOrders.test.jsx
- tests/components/DrugOrderEntry/addForm/AddForm.test.jsx
- tests/components/DrugOrderEntry/addForm/DraftDataTable.test.jsx
- tests/components/DrugOrderEntry/addForm/FreeText.test.jsx
- tests/components/DrugOrderEntry/index.test.jsx
- tests/components/breadCrumb/index.test.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/components/patientDashboard/index.test.jsx
- tests/components/searchDrug/index.test.jsx
- tests/components/tabs/DosageTab.test.js
- tests/components/tabs/Tabs.test.js
**JIRA TICKET NAME**
[OEUI-172](https://issues.openmrs.org/browse/OEUI-172) Remove error messages in test
**Summary**
- This PR fixes most of the warning messages being displayed when running the test cases.
> OEUI-172: Remove error messages when running test suites

- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/labOrderEntry/LabPanelFieldSet.jsx
- tests/components/labOrderEntry/LabEntryForm.test.jsx
- tests/components/labOrderEntry/LabPanelFieldSet.test.jsx
[OEUI-175: Users should not be able to remove lab test from panels](https://issues.openmrs.org/browse/OEUI-175)
When a user selects an option in the panel, some tests are selected, these selected tests should not be removable until the user un-selects the panel option.
> OEUI-175: Make lab tests from panel selection unremovable

- app/css/openmrs-owa-orderentry.css
- app/js/components/labOrderEntry/LabDraftOrder.jsx
- app/js/components/labOrderEntry/labData.js
- app/js/reducers/draftLabOrderReducer.js
- tests/reducers/draftLabOrderReducer.test.js
**JIRA TICKET NAME**
[OEUI-178](https://issues.openmrs.org/browse/OEUI-178) Add urgency button to the draft lab order
**Summary**
- This PR adds the urgency button to the draft lab orders
> OEUI-178: Adjust the urgency of a lab order

- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/labOrderEntry/LabPanelFieldSet.jsx
- app/js/components/labOrderEntry/LabTestFieldSet.jsx
- app/js/components/orderEntry/OrderEntryPage.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/components/orderentry/SelectOrderType.test.jsx
[OEUI-188](https://issues.openmrs.org/browse/OEUI-188) Reduce multiple re-rendering in app
- Reduce multiple re-rendering in application
> OEUI-188: Reduce Multiple re-rendering in app

- app/js/components/labOrderEntry/LabDraftOrder.jsx
- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/labOrderEntry/styles.scss
- app/js/reducers/draftLabOrderReducer.js
- app/js/utils/constants.js
- tests/components/labOrderEntry/LabDraftOrder.test.jsx
- tests/reducers/draftLabOrderReducer.test.js
**JIRA TICKET NAME**
[OEUI-218](https://issues.openmrs.org/browse/OEUI-218) Refactors Urgency logic and fix bugs around adding urgency
**Summary**
- This PR also refactor Urgency logic and fix bugs around adding urgency
> OEUI-218: Update Urgency logic and fix bugs around adding urgency

- app/css/openmrs-owa-orderentry.scss
- app/js/components/drugOrderEntry/index.jsx
- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/orderEntry/Accordion.jsx
- app/js/components/orderEntry/AllOrders.jsx
- app/js/components/orderEntry/DrugOrderDetails.jsx
- app/js/components/orderEntry/LabOrderDetails.jsx
- app/js/components/orderEntry/OrderEntryPage.jsx
- app/js/components/orderEntry/OrderHeader.jsx
- app/js/components/orderEntry/OrdersTable.jsx
- app/js/components/orderEntry/RenderOrderType.jsx
- app/js/components/orderEntry/SelectOrderType.jsx
- app/js/components/orderEntry/allOrdersMock.json
- app/js/components/orderEntry/styles.scss
- tests/components/orderentry/Accordion.test.jsx
- tests/components/orderentry/AllOrders.test.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/components/orderentry/OrdersTable..test.jsx
- tests/components/orderentry/SelectOrderType.test.jsx
[OEUI-216](https://issues.openmrs.org/browse/OEUI-216)
- Build out homepage based on new design mockups
> OEUI-216: Build Out New Homepage Design

- app/js/components/labOrderEntry/LabEntryForm.jsx
[OEUI-245: Fix bug that prevents creating of Lab Order.](https://issues.openmrs.org/browse/OEUI-245)
This pull request fixes the bug that prevents the creation of Lab Orders.
> OEUI-245: Fix bug preventing creation of lab orders

- app/js/components/button/IconButton.jsx
- app/js/components/orderEntry/OrderHeader.jsx
- app/js/components/orderEntry/styles.scss
- tests/components/button/IconButton.test.jsx
- tests/components/orderentry/OrderHeader.test.jsx
**JIRA TICKET**
[OEUI-228](https://issues.openmrs.org/browse/OEUI-228) - Display proper action buttons for the different order types on the order home page
> OEUI-228 : displaying proper action buttons for the different order types on the order home page

- app/js/components/drugOrderEntry/ActiveOrders.jsx
- app/js/components/drugOrderEntry/PastOrders.jsx
- app/js/components/drugOrderEntry/addForm/AddForm.jsx
- app/js/components/drugOrderEntry/addForm/FreeText.jsx
- app/js/components/drugOrderEntry/addForm/StandardDose.jsx
- app/js/components/drugOrderEntry/index.jsx
- app/js/reducers/careSettingReducer.js
- app/js/reducers/initialState.js
- tests/components/DrugOrderEntry/ActiveOrders.test.jsx
- tests/components/DrugOrderEntry/PastOrders.test.jsx
- tests/components/DrugOrderEntry/addForm/AddForm.test.jsx
- tests/components/DrugOrderEntry/addForm/FreeText.test.jsx
- tests/components/DrugOrderEntry/addForm/StandardDose.test.jsx
[OEUI-222: Take out the inpatient and outpatient care settings](https://issues.openmrs.org/browse/OEUI-222)
This pull request removes the inpatient/outpatient tabs(and settings) that are on the Drug Order page in the application. Consequently, the drug order functionality treats the patients as outpatients.
> OEUI-222: Remove the inpatient/outpatient option for drug orders

- app/js/components/drugOrderEntry/addForm/AddForm.jsx
- app/js/components/drugOrderEntry/addForm/DraftDataTable.jsx
- app/js/components/drugOrderEntry/index.jsx
- app/js/reducers/initialState.js
- tests/components/DrugOrderEntry/addForm/DraftDataTable.test.jsx
[OEUI-244](https://issues.openmrs.org/browse/OEUI-244) ---> Fix bug that prevents creating of Drug Order
> OEUI-244 - Fix bug that prevents creating of Drug Order

- .github/pull_request_template.md
**JIRA TICKET NAME**
[OEUI-248](https://issues.openmrs.org/browse/OEUI-248) Add PR template
**Summary**
- This PR adds a PR template to the repo
> OUEU-248: Add PR template

- app/css/openmrs-owa-orderentry.scss
- app/js/components/orderEntry/DrugOrderDetails.jsx
- app/js/components/orderEntry/LabOrderDetails.jsx
- app/js/components/orderEntry/OrderHeader.jsx
- app/js/components/orderEntry/styles.scss
[OEUI-259: Proper text formatting for order details on the orders list](https://issues.openmrs.org/browse/OEUI-259)
- This pull request fixes the text formatting issues on the orders page described in the ticket above.
> OEUI-259: Fix text fomatting issues on orders page

- app/js/components/drugOrderEntry/PastOrders.jsx
- app/js/components/drugOrderEntry/addForm/AddForm.jsx
- app/js/components/labOrderEntry/labData.js
- app/js/middlewares/errorMiddleware.js
- app/js/reducers/careSettingReducer.js
- app/js/reducers/index.js
- tests/actions/draftActions.test.js
- tests/components/labOrderEntry/LabEntryForm.test.jsx
- tests/components/labOrderEntry/LabPanelFieldSet.test.jsx
- tests/components/labOrderEntry/LabTestFieldSet.test.jsx
- webpack.config.js
[OEUI-273: Remove Commented Code from CodeBase](https://issues.openmrs.org/browse/OEUI-273)
- Sweep through the codebase by removing any commented code that has been written.
> OEUI-273: Remove Commented Code from CodeBase

- tests/components/DrugOrderEntry/addForm/AddForm.test.jsx
- tests/components/DrugOrderEntry/addForm/StandardDose.test.jsx
- tests/components/DrugOrderEntry/index.test.jsx
- tests/components/labOrderEntry/LabDraftOrder.test.jsx
- tests/components/labOrderEntry/LabEntryForm.test.jsx
- tests/components/labOrderEntry/LabPanelFieldSet.test.jsx
- tests/components/labOrderEntry/LabTestFieldSet.test.jsx
- tests/components/orderentry/OrderEntryPage.test.jsx
- tests/components/tabs/DosageTabs.test.js
[OEUI-275](https://issues.openmrs.org/browse/OEUI-275) mock text
- Remove usage of spy in tests
> OEUI-275: Remove usage of spy in tests

- app/js/components/orderEntry/Accordion.jsx
- app/js/components/orderEntry/AllOrders.jsx
- app/js/components/orderEntry/LabOrderDetails.jsx
- app/js/components/orderEntry/OrdersTable.jsx
- app/js/components/orderEntry/styles.scss
- package-lock.json
- tests/components/Draft.test.jsx
[OEUI-280 UI Improvements on Order List page](https://issues.openmrs.org/browse/OEUI-280)
- The order name was left-justified in the details column
- Only the date, not the time, is showed in the date column.  This eliminated wrapping and allow for the rows to be thinner.  
- The entire date and time can show when the row is expanded.
- For drugs, only the drug name is showing.
- The dosage, frequency etc....  are all show when the row is expanded.
> OEUI-280: UI Improvements on Order List page

- app/js/actions/fetchOrders.js
- app/js/components/orderEntry/AllOrders.jsx
- app/js/components/orderEntry/Paginate.jsx
- app/js/components/orderEntry/styles.scss
- package-lock.json
- tests/actions/fetchOrdersAction.test.js
- tests/components/orderentry/AllOrders.test.jsx
- tests/components/orderentry/Paginate.test.jsx
[OEUI-270: Fix bug in Order list Pagination](https://issues.openmrs.org/browse/OEUI-270)
- Fix bug that prevents the pagination on the orders home page list from working as it should.
> OEUI-270: Fix bug in Order list Pagination

- app/js/actions/fetchAllOrders.js
- app/js/components/drugOrderEntry/addForm/AddForm.jsx
- tests/actions/fetchAllOrdersAction.test.js
- tests/components/DrugOrderEntry/addForm/AddForm.test.jsx
[OEUI-285: Validate if drug order is active](https://issues.openmrs.org/browse/OEUI-285) 
- I wrote a function to check if there is an active drug order before adding the drug order in the draft list.
> OEUI-285: Validate if drug order is active

- app/js/components/orderEntry/Paginate.jsx
- app/js/components/orderEntry/styles.scss
[OEUI-286: Remove background color in pagination](https://issues.openmrs.org/browse/OEUI-286)
- Remove background color in pagination
> OEUI-286: Remove background color in pagination

- app/js/components/drugOrderEntry/addForm/AddForm.jsx
- app/js/components/drugOrderEntry/index.jsx
- app/js/components/orderEntry/AllOrders.jsx
[OEUI-292: Fix linter trailing white spaces warnings](https://issues.openmrs.org/browse/OEUI-292)
Fix linter trailing white spaces warnings
> OEUI-292: Fix linter trailing white spaces warnings

- app/js/components/drugOrderEntry/PastOrder.jsx
- app/js/components/drugOrderEntry/addForm/FreeText.jsx
- app/js/components/labOrderEntry/LabPanelFieldSet.jsx
- app/js/components/orderEntry/OrdersTable.jsx
- app/js/components/orderEntry/Paginate.jsx
- app/js/components/orderEntry/RenderOrderType.jsx
- app/js/components/orderEntry/SortAndFilter.jsx
- app/js/components/searchDrug/View.jsx
- app/js/components/tabs/DosageTabs.jsx
- app/js/components/tabs/Tabs.jsx
[OEUI-296: Remove unused states, props and variables](https://issues.openmrs.org/browse/OEUI-296)
- The purpose of this task is to remove unused states, props and variables from the codebase.
> OEUI:296: Remove unused states, props and variables

- app/js/components/setsOrderEntry/OrderSetForm.jsx
- tests/components/setOrderEntry/OrderSetForm.test.jsx
[OEUI-265: Save Order from Set to Draft Functionality](https://issues.openmrs.org/browse/OEUI-265)
- Save Order from Set to Draft Functionality
> OEUI-265: Save Order from Set to Draft Functionality

- package-lock.json
- package.json
- webpack.config.js
WOR-205: orderentry-owa build failling
> fix failing bamboo build

- app/js/components/orderEntry/OrdersTable.jsx
[OEUI-1234](https://issues.openmrs.org/browse/OEUI-301) OEUI-301: Rerouting Error when discontinuing order
- Fix for Rerouting Error when discontinuing an order
> OEUI-301: Rerouting Error when discontinuing order

- app/js/components/drugOrderEntry/index.jsx
- app/js/components/labOrderEntry/LabEntryForm.jsx
- app/js/components/orderEntry/AllOrders.jsx
- app/js/components/orderEntry/OrderEntryPage.jsx
- app/js/components/orderEntry/RenderOrderType.jsx
- tests/components/DrugOrderEntry/index.test.jsx
- tests/components/labOrderEntry/LabEntryForm.test.jsx
> OEUI-304: Add back functionality to patient dashboard

- app/js/translations/en.json
> UHM-4041: standardize lab status terminology

- app/js/middlewares/responseHandlerMiddleware.js
- app/js/translations/en.json
- app/js/translations/fr.json
- app/js/translations/ht.json
- package.json
- tests/middlewares/responseHandlerMiddleware.test.js
> UHM-4073: No confirmation displayed when order is canceled

- app/js/components/labOrderEntry/styles.scss
@mogoodrich 
please review this change.
> (UHM-4053) Column issues on Lab Ordering page when test name too long

- README.md
- Some formatting proposals (mostly across some paragraphs) with a focus on code formatting. There is no previous PR or issue related, so there is no collateral damage threat.
> Some formatting proposals 

- app/js/components/Draft.jsx
https://pihemr.atlassian.net/browse/UHM-4544
> UHM-4544 Lab Orders allows multiple submits

- tests/components/__snapshots__/Draft.test.jsx.snap
- tests/components/orderentry/__snapshots__/OrderEntryPage.test.jsx.snap
- webpack.config.js
Fixing the build. See https://bamboo.pih-emr.org/browse/MIREBALAIS-OEOWA-853
> Move development-specific parts of webpack into 'if' block

- app/js/components/orderEntry/OrderEntryPage.jsx
- app/js/components/orderEntry/styles.scss
- tests/components/orderentry/__snapshots__/OrderEntryPage.test.jsx.snap
https://pihemr.atlassian.net/browse/UHM-4565
> Improve draft order responsiveness

- app/js/components/orderEntry/OrderEntryPage.jsx
> UHM-4934: Create "circular workflow" for adding Lab Orders from the Lab Workflow module

- app/js/utils/helpers.js
- tests/components/labOrderEntry/__snapshots__/LabEntryForm.test.jsx.snap
- tests/components/labOrderEntry/__snapshots__/LabPanelFieldSet.test.jsx.snap
> UHM-7070: Lab OWA test result not showing short names
